# Generated by Django 3.0.8 on 2020-07-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M2app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
    ]
