# Generated by Django 3.0.8 on 2020-07-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M2app', '0002_loginform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='CPassword',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='DOB',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Firstname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Lastname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Phone',
            field=models.CharField(max_length=12),
        ),
    ]
